apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: component-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/sample-image@sha256:1480312923177b4dc61c8dd0c1709fd8a62eea9d587355dfcbc68077c0c2f58b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
